### ISSUE TITLE
Search Bar

### ISSUE THREAD

**Issue by IbrahimMoftah329** [IbrahimMoftah329/Capstone#28]
expected behavior

topic
to search based off of name and description

semester
to search based off of semester

professor
to search based off of professor

**Comment by Calv718** [comment]
Added full functionality for searching decks by topic, professor, or semester.

**Comment by Calv718** [comment]
Added functionality to backend routes, controllers, and schemas to support adding a favorite deck/quiz to a user.
Added functionality to frontend components to support filtering and display of favorited decks/quizzes/quiz attempts/deck flashcards.

**Comment by Calv718** [comment]
Still want to add:

- allow study mode from search bar
- add number of times deck/quiz has been favorited
